### PR TITLE
Add support for Haiku

### PR DESCRIPTION
**Pull request by nielx**
This commit adds support for Haiku and obsoletes PR #53

### CODE REVIEW

**Comment by kallisti5** [comment]
Thanks @nielx !! @alexcrichton any chance of getting this build fix merged? Lots of stuff still depends on net2

**Comment by alexcrichton** [comment]
Sorry I do not maintain this crate any more.

**Comment by kallisti5** [comment]
Sorry Alex (not @'ing to not bug you)

@pfmooney I can independently confirm this fixes the net2 build on Haiku under Rust 1.44:

```
/Data/net2-rs> uname -a
Haiku shredder 1 hrev54540 Sep  2 2020 06:57:26 x86_64 x86_64 Haiku
```

**Before PR:**
```
/Data/net2-rs> cargo build
    Updating crates.io index
  Downloaded cfg-if v0.1.10
  Downloaded libc v0.2.76
  Downloaded 2 crates (514.4 KB) in 1.06s
   Compiling libc v0.2.76
   Compiling cfg-if v0.1.10
   Compiling net2 v0.2.34 (/Data/net2-rs)
error[E0432]: unresolved import `libc::TCP_KEEPIDLE`
   --> src/ext.rs:673:13
    |
673 |         use libc::TCP_KEEPIDLE as KEEPALIVE_OPTION;
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `TCP_KEEPIDLE` in the root

error[E0425]: cannot find value `IPV6_ADD_MEMBERSHIP` in this scope
    --> src/ext.rs:1135:50
     |
1135 |         set_opt(self.as_sock(), v(IPPROTO_IPV6), IPV6_ADD_MEMBERSHIP,
     |                                                  ^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `IP_ADD_MEMBERSHIP`
     | 
    ::: /boot/home/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.76/src/unix/haiku/mod.rs:831:1
     |
831  | pub const IP_ADD_MEMBERSHIP: ::c_int = 12;
     | ------------------------------------------ similarly named constant `IP_ADD_MEMBERSHIP` defined here

error[E0425]: cannot find value `IPV6_DROP_MEMBERSHIP` in this scope
    --> src/ext.rs:1154:50
     |
1154 |         set_opt(self.as_sock(), v(IPPROTO_IPV6), IPV6_DROP_MEMBERSHIP,
     |                                                  ^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `IP_DROP_MEMBERSHIP`
     | 
    ::: /boot/home/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.76/src/unix/haiku/mod.rs:832:1
     |
832  | pub const IP_DROP_MEMBERSHIP: ::c_int = 13;
     | ------------------------------------------- similarly named constant `IP_DROP_MEMBERSHIP` defined here

error[E0308]: mismatched types
  --> src/sys/unix/mod.rs:54:23
   |
54 |             ioctl(fd, FIOCLEX);
   |                       ^^^^^^^ expected `i32`, found `u64`
   |
help: you can convert an `u64` to `i32` and panic if the converted value wouldn't fit
   |
54 |             ioctl(fd, FIOCLEX.try_into().unwrap());
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0308, E0425, E0432.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `net2`.

To learn more, run the command again with --verbose.
```



**After:**
```
/Data/net2-rs> cargo build
   Compiling net2 v0.2.34 (/Data/net2-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 2.44s

/Data/net2-rs> cargo test
   Compiling net2 v0.2.34 (/Data/net2-rs)
    Finished test [unoptimized + debuginfo] target(s) in 1.83s
     Running target/debug/deps/net2-88a7a404c42fb69f

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/all-e93a1b0ec1073f57

running 2 tests
test smoke_build_listener ... ok
test smoke_build_listener_v6 ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests net2

running 1 test
test src/lib.rs -  (line 27) ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

```

**Comment by pfmooney** [comment]
> @pfmooney I can independently confirm this fixes the net2 build on Haiku under Rust 1.44:

Please pardon the delay.  I'll be cutting a new release of `net2` to include the change shortly.

**Comment by pfmooney** [comment]
> I'll be cutting a new release of `net2` to include the change shortly.

v0.2.35 has been published to crates.io

**Comment by nielx** [comment]
> > I'll be cutting a new release of `net2` to include the change shortly.
> 
> v0.2.35 has been published to crates.io

Thank you! This will make the experience of Rust on Haiku a lot better.
